#!/usr/bin/env php
<?php

declare(strict_types=1);

use Dotenv\Dotenv;
use Yiisoft\Yii\Runner\Console\ConsoleApplicationRunner;

require_once __DIR__ . '/vendor/autoload.php';

Dotenv::createImmutable(__DIR__)->safeLoad();

$debug = filter_var($_SERVER['APP_DEBUG'] ?? false, FILTER_VALIDATE_BOOL);

$environment = $_SERVER['APP_ENV'] ?? 'prod';

$consoleRunner = new ConsoleApplicationRunner(
    rootPath: __DIR__,
    debug: $debug,
    checkEvents: $debug,
    environment: is_string($environment) ? $environment : 'prod',
);

$consoleRunner->run();
